catalog:
  '@antfu/eslint-config': ^4.17.0
  '@eslint/config-array': ^0.21.0
  '@nuxt/eslint': 1.6.0
  '@nuxt/icon': ^1.15.0
  '@nuxt/ui': 3.2.0
  '@nuxtjs/color-mode': ^3.5.2
  '@tailwindcss/vite': ^4.1.11
  '@testing-library/vue': ^8.1.0
  '@vitejs/plugin-vue': ^6.0.0
  '@vitest/ui': ^3.2.4
  '@vue/test-utils': ^2.4.6
  eslint: ^9.0.0
  fflate: ^0.8.2
  jsdom: ^26.1.0
  nuxt: ^4.0.0
  nuxt-eslint-auto-explicit-import: ^0.1.1
  tailwindcss: ^4.1.11
  typescript: ^5.8.3
  vitest: ^3.2.4
  vue: ^3.5.17
  vue-router: ^4.5.1
  vue-tsc: ^3.0.3
